tree-sitter/tree-sitter-cpp

- corpus/declarations.txt
- grammar.js
- src/grammar.json
I'm doing some experimentation related to Mozilla's searchfox tool and it choked on [`class ServiceWorkerRegistrarSaveDataRunnable final : public Runnable`](https://searchfox.org/mozilla-central/source/dom/serviceworkers/ServiceWorkerRegistrar.cpp#824) in my experimentation so I thought I'd try my hand at a fix*.  It's okay if you'd rather not take random piece-meal patches like this and instead take a more comprehensive C++11 update/other.  I'm just happy to have this tool available and that it supports such great error recovery so small issues like this aren't a big deal!  Thanks for the amazing tool!
I've linked to the relevant docs in the first commit.  Note that http://www.nongnu.org/hcb/#class-virt-specifier which is one of the sources this repo links to cites "explicit" as a …
> Support C++11 class-virt specifier for "class A final {}" cases.

- corpus/declarations.txt
- grammar.js
- package.json
- src/grammar.json
In an attempt to expand on #6 and support override/final for functions
I've attempted some changes in this patch.
The relevant specs are:
https://en.cppreference.com/w/cpp/language/override
https://en.cppreference.com/w/cpp/language/final
Given the test input:
```
struct B : A {
int foo() override { return 2; }
int pho() final { return 3; }
int bar() const override { return 4; }
int baz() const final { return 5; }
int bag() const final override { return 6; }
int bah() const override final { return 7; }
};
```
The test results come out:
```
(translation_unit (struct_specifier (type_identifier) (base_class_clause (type_identifier)) (field_declaration_list
(function_definition (primitive_type) (function_declarator (field_identifier) (parameter_list)) (ERROR) (compound_statement …
```
> Add support for function virtual specifiers.

- corpus/statements.txt
- grammar.js
- src/grammar.json
The goal of this patch is to handle to keyword "throw".
```cpp
void main() {
throw e;
throw x + 1;
throw "exception";
}
```
> Handle throw

- corpus/declarations.txt
- grammar.js
- src/grammar.json
- src/node-types.json
This implements support for the following:
* Template constructors defined outside class definition (Fixes #50)
* Nested template function definitions outside class definition
* Template template parameters
* Name-specifiers are now (correctly) optional in template parameters
> Various improvements to template parsing

- corpus/declarations.txt
- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/node-types.json
Fixes #27
For information about parameter packs, see
https://en.cppreference.com/w/cpp/language/parameter_pack
Most expansion loci should work with this commit since it is implemented
as an expression, so anywhere an expression is valid, parameter pack
expansions will be parsed.
This commit also adds support for:
* The sizeof... operator (as an alternative to sizeof)
* Lambda captures can optionally start with a default capture along with
other captures
* Lambda function declarators (the parameter list) are optional
Tests added for the following parameter pack expansion loci:
* Function parameter and argument lists
* Template argument lists
* Base class specifiers and member initializer lists
* Lambda captures
> Support for parameter pack expansions and improvements to lambda expressions

- corpus/declarations.txt
- grammar.js
- src/grammar.json
- src/node-types.json
They are valid in global, namespace, and block scope as a block declaration, as well as in a class body as a member declaration.
> Add support for static_assert declarations

- src/scanner.cc
- test/corpus/expressions.txt
Regenerate grammar on top of:
https://github.com/tree-sitter/tree-sitter-c/pull/36
And support all raw string types.
For reference:
https://en.cppreference.com/w/cpp/language/string_literal
> Add (u|u8|U|L)R raw string literal support

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
No restriction in the standard and it exists in real life:
https://hg.mozilla.org/mozilla-central/file/tip/dom/indexedDB/ActorsParent.cpp#l16956
> Concatenated strings can contain raw string literals

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/definitions.txt
```cpp
class DefaultArea final : public Area {
explicit DefaultArea(HTMLAreaElement* aArea);
};
``` 
was leading to an error so fix it.
For reference:
https://en.cppreference.com/w/cpp/language/explicit
> Fix explicit ctor declaration and support explicit with condition (c++20)

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
- test/corpus/statements.txt
For reference:
https://en.cppreference.com/w/cpp/language/if
https://en.cppreference.com/w/cpp/language/while
https://en.cppreference.com/w/cpp/language/switch
And this patch handles C++17 init-statements too.
> Fix declaration in if/switch/while conditions

- grammar.js
- src/grammar.json
- test/corpus/expressions.txt
Array assignment expressions were broken in https://github.com/tree-sitter/tree-sitter-cpp/commit/df7bc44e3387d1ba9e77f3ac22a1acb1d30f90ab which added more
support for structured binding declarators. We need to add a dynamic
precedence that is lower than that of an assignment expression so that
code is parsed as an assignment expression before it's parsed as a
structured binding.
@maxbrunsfeld feel free to let me know a better way to assign the precedence, here. I know it needs to be lower than that of an assignment expression, but I'm not sure I picked the best way to do it.
> Fix array assignment expressions so they don't parse as structured bindings

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
Improve parsing of friend declarations when using c++11 simple type specifier
Also resolves possible erroneous parsing of a friend declaration attempting to define a new class.
> Improve parsing of friend declarations 

- grammar.js
- package.json
- src/grammar.json
- src/node-types.json
- test/corpus/microsoft.txt
This PR updates tree-sitter-c to 0.16.1 to support Microsoft-specific modifiers as introduced in https://github.com/tree-sitter/tree-sitter-c/pull/40.
> Add support for Microsoft-specific modifiers

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
Constructor declarations can have the same decl-specifiers as
constructor definitions. This adds a new rule to match as many
"constructor specifiers" that are present in any order before the
function decl itself, and adds the rule to constructor declarations and
constructor definitions.
The cast operator can also have any of these specifiers in any order
before the declaration, so this commit also changes the cast operator
declaration and definition to use the new rule as well.
Finally, constructor declarations and cast operator declarations can be
part of a template declaration in addition to the definitions, so add
them both to the template_declaration rule.
> Fixes for constructor declarations

- queries/highlights.scm
As mentioned in issue #90, this one-liner should enable syntax highlighting for raw string literals
> Highlight raw string literals

- grammar.js
- queries/highlights.scm
- src/grammar.json
- src/node-types.json
C++20 introduces language support for coroutines, using three new
keywords and related language constructions.
* co_await is a unary operator.
* co_return introduces a statement, and works just like return or throw.
* co_yield similarly introduces a statement, but cannot stand for
itself.
Add support for these facilities to the parser and highlighter.
> Support C++20 coroutines

- test/corpus/expressions.txt
- test/corpus/statements.txt
Test cases for correct parsing of co_return and co_yield statements as
well as co_await expressions are added to the corpus.
> Add coroutine tests

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
Add support for the C++11 ref-qualifier syntax to the grammar. Add tests
that ref-qualifiers are parsed properly on both declarations and
definitions.
See http://eel.is/c++draft/dcl.fct and http://eel.is/c++draft/dcl.decl.general#nt:ref-qualifier .
https://en.cppreference.com/w/cpp/language/member_functions#ref-qualified_member_functions
Fixes #111
> Ref-qualifiers on functions

- grammar.js
- queries/highlights.scm
- src/grammar.json
- src/node-types.json
- test/corpus/ambiguities.txt
- test/corpus/declarations.txt
- test/corpus/definitions.txt
- test/corpus/expressions.txt
- test/corpus/statements.txt
- test/corpus/types.txt
!! Breaking change due to restructuring and renaming of scoped identifiers !!
Scoped identifier rules have been renamed to "qualified_x_identifier" and all variants are aliased so they appear as simply "qualified_identifier" in the syntax tree. This name better reflects the c++ standard's language describing this concept.
Qualified identifier rules are now always the "parent" with a right associative rule that lets them nest indefinitely. Each rule terminates with some kind of non-scope identifier.
This commit also adds support for the 'template' keyword where required to disambiguate dependent template names. Field accessors (., ->) can be followed by keyword template before a template method. The scope resolution operator can be immediately followed by the 'template' keyword to indicate …
> Overhaul scoped identifier rules and add dependent name support

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/concepts.txt
- test/corpus/declarations.txt
- test/corpus/expressions.txt
- test/corpus/statements.txt
- test/corpus/types.txt
@theHamsta this adds support for one of the two remaining things for concepts.
The function declarator one is a bit heavier since it requires a _lot_ more parse states and grows the parser pretty substantially, so I want to play with it a bit more first.
> Add support for constraints on placeholder type specifiers

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
- test/corpus/expressions.txt
Continuation of #104 (the original fork the PR was compared against was deleted).
Refs:
https://en.cppreference.com/w/cpp/language/operator_comparison#Three-way_comparison
https://en.cppreference.com/w/cpp/language/default_comparisons
https://en.cppreference.com/w/cpp/language/operator_precedence
Fixes #114
Closes #104
> Add support for default comparisons and the three way comparison operator

- grammar.js
- src/grammar.json
- src/node-types.json
- src/tree_sitter/parser.h
- test/corpus/concepts.txt
- test/corpus/expressions.txt
Fold Expressions
==========
This PR adds rules to recognize fold expressions.
Example:
```cpp
int t = (... + IndexOf<T>);
```
currently produces an error because the ellipsis is unrecognized:
```
(translation_unit [0, 0] - [0, 27]
(declaration [0, 0] - [0, 27]
type: (primitive_type [0, 0] - [0, 3])
declarator: (init_declarator [0, 4] - [0, 26]
declarator: (identifier [0, 4] - [0, 5])
value: (parenthesized_expression [0, 8] - [0, 26]
(ERROR [0, 9] - [0, 12])
(unary_expression [0, 13] - [0, 25]
argument: (template_function [0, 15] - [0, 25]
name: (identifier [0, 15] - [0, 22])
arguments: (template_argument_list [0, 22] - [0, 25]
(type_descriptor [0, 23] - [0, 24]
type: (type_identifier [0, 23] - [0, 24])))))))))
```
but with this PR, the ellipsis is recognized and produces a …
> Implement fold expressions and more complete requires clauses

- .gitignore
- Package.swift
- bindings/swift/TreeSitterCPP/cpp.h
Swift's package manager can build C/C++ sources and use headers to expose functions to Swift. The standard tree-sitter parser project layout just requires a little extra configuration to make it happy.
Grammars with SPM support to this date:
- https://github.com/tree-sitter/tree-sitter-javascript
- https://github.com/tree-sitter/tree-sitter-php
- https://github.com/tree-sitter/tree-sitter-c
- https://github.com/tree-sitter/tree-sitter-java
- https://github.com/tree-sitter/tree-sitter-rust
> Swift Package Manager

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
- test/corpus/definitions.txt
Some time ago I contributed support for function-try-block (#169). I just noticed that the implementation is not correct.
In case of constructor, the initializer list must appear after `try`, like here:
```cpp
Test() try : member(5) {} catch (...) {}
```
This complicates things a bit because we can not reuse the `try_statement` production.
There were also two other cases where try block is allowed and was missing: in inline member functions and in conversion operators definitions. I extended these two to allow for `try_statement` in body.
Sorry for the mess and thanks in advance for checking this PR!
> Correct function-try-block parsing

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
This is an alternative implementation of #170.
This adds support for the alternative operator representations in unary, binary, and assignment expressions, as well as when using in explicit operator calls and overload declarations/definitions.
This does _not_ support full token substitution the preprocessor performs (these alternate tokens can be substituted _anywhere_ the tokens they represent appear, but in this grammar they are only supported in the above expressions).
This also does _not_ add support for alternate token representations of the brace tokens ('{', '}', '[', ']') or preprocessor directives ('#', '##')
Resolves #170
Resolves #94
> Add support for alternative operator representations (#94)

- grammar.js
- package.json
- queries/injections.scm
- src/grammar.json
- src/node-types.json
- src/scanner.cc
- test/corpus/declarations.txt
- test/corpus/expressions.txt
In raw-strings, the delimiter can be used to indicate embedded language:
```
R"css( body { background: red; } )css"
```
This patch adds the delimiter (if present) and raw-string content as children of the raw_string_literal.
These can be used to parse the content with an injected grammar.
Fixes https://github.com/tree-sitter/tree-sitter-cpp/issues/159
> Include rawstring delimiters in the tree, use for injections

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/declarations.txt
This commit adds support for
```cpp
using AttrAlias [[deprecated]] = int;
```
Reference: https://en.cppreference.com/w/cpp/language/type_alias
> support attribute in alias declaration

- grammar.js
- src/grammar.json
- src/node-types.json
Gotta love C++, this is valid:
```cpp
#include <stdio.h>
int main() {
int x = 1;
int bitand y = x;
printf("x: %d, y: %p\n", x, bitand y);
}
```
> feat: add missing fold operators

- .appveyor.yml
Update used Windows image and NodeJS version to the latest LTS.
See:
- https://www.appveyor.com/docs/windows-images-software/#operating-system
- https://www.appveyor.com/docs/windows-images-software/#node-js
- https://endoflife.date/nodejs
Similar to https://github.com/tree-sitter/tree-sitter-c/pull/138
> Fix AppVeyor CI builds

- src/scanner.c
This suppresses a warning when using clang for compilation (and probably also with other C compilers).
If `skip` is intended to be kept (e.g. to be consistent with other scanner implementations) the warning could be suppressed using compiler specific pragmas.
> refactor: remove unused function `skip` in scanner

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
This change allows commas inside subscripts.
```cpp
auto x = a[1, 2, 3];
```
From C++23, array subscripts work like arguments to `operator[]` as an n-ary function.
Before C++23, `operator[]` must be a unary function, but before C++20, it's possible to use the comma operator inside subscript expressions - and this is done in libraries that use expression templates to achieve multidimensional array syntax.
Use of the comma operator in subscript expressions was deprecated in C++20 to make way for the C++23 change to n-ary `operator[]`.
> Support multidimensional subscripts

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
This change allows operators (not just fields/member functions) as dependent template expressions.
```cpp
auto x = y.template operator()<int>();
```
This syntax is used e.g. to call C++20 lambda expressions with a template head where the template arguments are not function arguments and therefore cannot be deduced.
```cpp
[]<typename> () {}.template operator()<int>();
```
> Support dependent operator templates

- queries/tags.scm
This PR adds new tags queries to `tags.scm` to support code search on Github.com.
> Adds GH tags queries

- bindings/rust/lib.rs
Context: `TAGS_QUERY`/`TAGGING_QUERY` as a const is used by [Tabby](https://github.com/TabbyML/tabby) for LLM-based autocompletion. Other `tree-sitter` libraries for other languages expose this constant: [`tree-sitter-ruby`](https://github.com/tree-sitter/tree-sitter-ruby/blob/f257f3f57833d584050336921773738a3fd8ca22/bindings/rust/lib.rs#L61), [`tree-sitter-go`](https://github.com/tree-sitter/tree-sitter-go/blob/ff86c7f1734873c8c4874ca4dd95603695686d7a/bindings/rust/lib.rs#L57), etc.
Exposing the same const for `tree-sitter-cpp`.
Related: https://github.com/tree-sitter/tree-sitter-c/pull/173
> Add TAGS_QUERY to rust bindings

- grammar.js
- src/grammar.json
- src/node-types.json
- src/tree_sitter/parser.h
- test/corpus/expressions.txt
Currently, there is an ambiguity in parsing fold expressions and parenthesized assignment expressions. This is described in issues #201 and #212.
This arises in the following trace:
```
( <id>    =
^ where we are here
```
The crux of the issue is that we do not know whether to shift the `=` forward, or to reduce the `<id>` to an `expression_not_binary`. If we do the former, we can no longer parse a fold expression, which expects `<exp> <fold_operator> '...'`. If we do the latter, we can no longer parse a parenthesized assignment expression, as an assignment expression does not permit arbitrary expressions to appear on the LHS.
The current behavior is that `tree-sitter-cpp` will reduce the `<id>`, and thus fail to parse any parenthesized assignment expression. Unfortunately, these are …
> disambiguate fold vs parenthesized assignment

- package.json
Running `npm run build` was defaulting to node's `node-gyp` version (apparently 9.x on my machine):
```shell
$ npm install
...
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.6.1 | darwin | arm64
...
Dnode_gyp_dir=/Users/khiner/.nvm/versions/node/v20.6.1/lib/node_modules/npm/node_modules/node-gyp',
```
This PR follows the config in the `package.json` of [tree-sitter-json](https://github.com/tree-sitter/tree-sitter-json), which I understand to be a good standard since it's used as an example in tree-sitter's documentation.
> Add node-gyp 10 to dev dependencies to fix build error

- src/scanner.c
- Add space after type casts and `sizeof`
- `RAW_STRING_DELIMITER_MAX` -> `MAX_DELIMITER_LENGTH` (more intuitive?)
- Remove the `scan` function and inline its contents
- Replace `_Static_assert` with `static_assert`
- Provided by `assert.h` since C11
- Manually defined as `assert` otherwise
- Some minor nitpicks
> chore(scanner): formatting improvements

- grammar.js
- src/grammar.json
- test/corpus/ambiguities.txt
This PR aims at fixing parsing of ambiguous expressions as mentioned in issue #231.
Consider for example the following code:
```cpp
if (x.foo < 0 || bar >= 1)
break;
```
This is currently recognized as an assignment ( of template method x.foo<...> to value 1) instead of the logical disjunction of two comparisons.
My understanding is that, for some reason, the prec.right in front of the field_expression's rule in the grammar prevents the parser from forking when "x.foo" is on the stack and forces the parsing of a template method instead.
I thus removed the prec.right annotation and added a conflict between field_expression, template_method and template_type.
In addition, I added a prec.dynamic annotation in front of field_identifier to avoid the reduction to a template method when reducing …
> Fixing ambiguities between template methods and comparisons

- .github/workflows/ci.yml
- Package.resolved
- Package.swift
- package-lock.json
- package.json
- src/grammar.json
- src/node-types.json
- src/tree_sitter/array.h
- src/tree_sitter/parser.h
Based on a couple of the open PRs and comments, it seems like this grammar needs a couple dependencies updated. Let me know if I missed anything!
I updated the tree-sitter-cli dependency to 0.25 and tree-sitter-c to its latest ABI 14 release, and then regenerated the parser with abi 14. It also looked like the CI job needed to be told to stay on version 14 for the time being.
> update dependencies and swift bindings

- grammar.js
- src/grammar.json
- test/corpus/declarations.txt
> feat: allow extern template instantiations

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/reflection.txt
Three commits here for three really huge c++26 features. Included corpus tests that pull most of the examples from the ISO papers themselves.
This adds support for all the language changes introduced in P2996 which
was recently voted into the upcoming c++26 standard.
This includes:
- reflection expressions: the reflect operator (`^^`) followed by
expressions, type descriptors, or the global namespace (`::`)
- splice specifiers/expressions: `[: expression :]`, which can appear as a
type, expression, alias descriptor, and more.
- `consteval` blocks: similar to static_asserts but have been introduced
specifically to allow constant evaluation side effects to occur at
specific places in code
Related to reflection, annotations use the same syntax as attributes,
but begin with an `=` and support …
> feat!: add support for reflection
